version: "3"

services:
  nginx:
    build: requirements/nginx
    image: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
      - adminer
      - ftp
    networks:
      - inception_network

  wordpress:
    build: requirements/wordpress
    image: wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception_network
    depends_on:
      - mariadb

  mariadb:
    build: requirements/mariadb
    image: mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception_network
    
  static_website:
    build:  requirements/bonus/static_website
    image: static_website
    restart: always
    networks:
      - inception_network
  
  adminer:
    build: requirements/bonus/adminer
    image: adminer
    restart: always
    networks:
      - inception_network
    depends_on:
      - mariadb
  
  redis_cache:
    build: requirements/bonus/redis_cache
    image: redis_cache
    restart: always
    networks:
      - inception_network
  ftp:
    build: requirements/bonus/ftp_server
    image: ftp
    restart: always
    ports:
      - "21:21"
      - "40000-40009:40000-40009"
    env_file:
      - .env
    volumes:
      - wordpress_data:/content
    networks:
      - inception_network
    depends_on:
      - wordpress

volumes:
  wordpress_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /Users/nelidris/data/wordpress_data
    #   o: bind
  mariadb_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /Users/nelidris/data/mariadb_data
    #   o: bind

networks:
  inception_network:
    driver: bridge