version: "3.9"

services:
  nginx:
    build: requirements/nginx
    image: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception_network

  wordpress:
    build: requirements/wordpress
    image: wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception_network
    depends_on:
      - mariadb

  mariadb:
    build: requirements/mariadb
    image: mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception_network
    
  static_website:
    build:  requirements/bonus/static_website
    image: static_website
    restart: always
    networks:
      - inception_network

volumes:
  wordpress_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /Users/nelidris/data/wordpress_data
    #   o: bind
  mariadb_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /Users/nelidris/data/mariadb_data
    #   o: bind

networks:
  inception_network:
    driver: bridge