version: "3.9"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/
    depends_on:
      - wordpress
      - adminer
      - ftp
    networks:
      - inception_network

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www
    env_file:
      - .env
    networks:
      - inception_network
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception_network
  
  adminer:
    container_name: adminer
    build: requirements/bonus/adminer
    restart: always
    networks:
      - inception_network
    depends_on:
      - mariadb
  
  redis:
    container_name: redis
    build: requirements/bonus/redis_cache
    restart: always
    networks:
      - inception_network
  ftp:
    container_name: ftp
    build: requirements/bonus/ftp_server
    restart: always
    ports:
      - "21:21"
      - "40000-40009:40000-40009"
    env_file:
      - .env
    volumes:
      - wordpress_data:/content
    networks:
      - inception_network
    depends_on:
      - wordpress
  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/personal_choice
    ports:
      - "8080:8080"
    networks:
      - inception_network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/nelidris/data/wordpress_data
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/nelidris/data/mariadb_data
      o: bind

networks:
  inception_network:
    driver: bridge